import { useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Text, View } from 'react-native';
import { Screen } from '@/components/ui/Screen';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { TextField } from '@/components/ui/TextField';
import { hubStyles as st, usePlayHub } from '@/components/PlayHubPanels';
import { useAppStore } from '@/store/useAppStore';
import { usePlayHubStore } from '@/store/usePlayHubStore';
import { compatibleWindows, localDateTime } from '@/lib/playHub';
import { formatBRL } from '@/lib/payments';
import { getSport } from '@/constants/sports';

export default function BoraScreen(){
  const params=useLocalSearchParams<{teamId?:string;establishmentId?:string;fieldId?:string}>();const {data,error,loading,refresh}=usePlayHub();
  const app=useAppStore();const mine=app.peladas.filter(t=>app.isAdmin(app.currentPlayerId,t.id));const fields=app.fields.filter(f=>app.establishments.some(e=>e.id===f.establishmentId&&e.ownerPlayerId===app.currentPlayerId)&&!data.venues.some(v=>v.establishment_id===f.establishmentId&&v.status!=='accepted'));
  const [team,setTeam]=useState(params.teamId??mine[0]?.id??'');const [field,setField]=useState(fields.find(f=>f.establishmentId===params.establishmentId)?.id??fields[0]?.id??'');
  const directorySlots=params.fieldId?data.slots.filter(s=>s.field_id===params.fieldId):data.slots;
  const [date,setDate]=useState('');const [time,setTime]=useState('18:00');const [until,setUntil]=useState('20:00');const [level,setLevel]=useState('all');
  const [duration,setDuration]=useState('60');const [regular,setRegular]=useState('');const [price,setPrice]=useState('');const [sport,setSport]=useState('all');const [query,setQuery]=useState('');
  const [mode,setMode]=useState('offers');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);
  async function run(action:string,payload:Record<string,unknown>){setBusy(true);try{await usePlayHubStore.getState().act(action,payload);setNotice('Salvo. Solicitar/confirmar reserva não gera pagamento automático.');}catch(e){setNotice(e instanceof Error?e.message:'Falha ao salvar.');}finally{setBusy(false);}}
  async function create(which:'window'|'slot'){try{const startsAt=localDateTime(date,time);await run(which==='window'?'window_create':'slot_create',which==='window'?{teamId:team,startsAt,endsAt:localDateTime(date,until),level}:{fieldId:field,startsAt,durationMinutes:Number(duration),regularPrice:Number(regular.replace(',','.')),offerPrice:Number(price.replace(',','.'))});}catch(e){setNotice(e instanceof Error?e.message:'Data inválida.');}}
  return <Screen><Button small variant="ghost" label="Voltar" onPress={()=>router.back()} /><Text style={st.title}>Horários e desafios</Text><Text style={st.copy}>Oferta real não é publicidade. O dono confirma a reserva; um desafio também precisa do aceite do outro time.</Text>
    <View style={st.row}>{[['offers','Oportunidades'],['manage','Publicar'],['requests','Meus pedidos']].map(([id,label])=><Button key={id} small variant={mode===id?'primary':'outline'} label={label} onPress={()=>setMode(id)} />)}</View>
    <Button small variant="ghost" label="Atualizar horários" loading={loading} onPress={()=>void refresh()} />{!!(notice||error)&&<Text accessibilityLiveRegion="polite" style={st.copy}>{notice||error}</Text>}
    {mode==='offers'&&<><Text style={st.copy}>Time solicitante (somente os que você administra)</Text><View style={st.row}>{mine.map(t=><Button key={t.id} small variant={team===t.id?'primary':'outline'} label={t.name} onPress={()=>setTeam(t.id)} />)}</View><TextField label="Campo ou bairro" value={query} onChangeText={setQuery} />
      <View style={st.row}>{['all',...new Set(data.slots.map(s=>s.sport_id))].map(id=><Button key={id} small variant={sport===id?'primary':'outline'} label={id==='all'?'Todos':getSport(id).label} onPress={()=>setSport(id)} />)}</View>
      {params.fieldId&&<Text style={st.copy}>Horários apenas do campo escolhido. A disponibilidade é revalidada ao pedir a reserva.</Text>}
      {!directorySlots.length&&<Text style={st.copy}>Nenhum horário de oportunidade disponível. Não mostramos disponibilidade inventada.</Text>}
      {directorySlots.filter(s=>(sport==='all'||s.sport_id===sport)&&`${s.field_name} ${s.address??''}`.toLowerCase().includes(query.toLowerCase())).map(s=><Card key={s.id} style={st.card}><Text style={st.title}>{getSport(s.sport_id).icon} {s.field_name}</Text><Text style={st.copy}>{new Date(s.starts_at).toLocaleString('pt-BR')} · {s.duration_minutes} min · {s.address}</Text><Text style={st.title}>{formatBRL(s.offer_price)} <Text style={st.copy}>em vez de {formatBRL(s.regular_price)} pelo horário completo</Text></Text><Text style={st.copy}>Desconto do campo, sem patrocínio. Valor total do horário; rateio entre times precisa ser combinado.</Text><Button small label="Pedir reserva para meu time" disabled={busy||!mine.some(t=>t.id===team&&t.sportId===s.sport_id)} onPress={()=>void run('slot_request',{slotId:s.id,teamId:team})} />
        {compatibleWindows(s,data.windows,team).map(w=><View key={w.id}><Text style={st.copy}>{w.team_name} está disponível · {w.level==='all'?'Todos os níveis':w.level}</Text><Button small variant="outline" label={`Desafiar ${w.team_name} neste campo`} disabled={busy||!mine.some(t=>t.id===team&&t.sportId===s.sport_id)} onPress={()=>void run('slot_request',{slotId:s.id,teamId:team,opponentId:w.pelada_id})} /></View>)}
      </Card>)}<Text style={st.title}>Times procurando adversário</Text>{data.windows.map(w=><View key={w.id}><Text style={st.copy}>{w.team_name} · {getSport(w.sport_id).label} · {new Date(w.starts_at).toLocaleString('pt-BR')} até {new Date(w.ends_at).toLocaleTimeString('pt-BR')}</Text>{app.isAdmin(app.currentPlayerId,w.pelada_id)&&<Button small variant="ghost" label="Retirar disponibilidade" disabled={busy} onPress={()=>void run('window_hide',{id:w.id})} />}</View>)}</>}
    {mode==='manage'&&<Card style={st.card}><Text style={st.title}>Publicar disponibilidade</Text><TextField label="Data (AAAA-MM-DD)" value={date} onChangeText={setDate} placeholder="2026-10-20" /><TextField label="Início (HH:mm)" value={time} onChangeText={setTime} />
      {mine.length>0&&<><Text style={st.title}>Meu time quer um desafio</Text><View style={st.row}>{mine.map(t=><Button small key={t.id} variant={team===t.id?'primary':'outline'} label={t.name} onPress={()=>setTeam(t.id)} />)}</View><TextField label="Disponível até (HH:mm)" value={until} onChangeText={setUntil} /><View style={st.row}>{[['all','Todos'],['beginner','Iniciante'],['intermediate','Intermediário'],['advanced','Avançado']].map(([id,label])=><Button key={id} small variant={level===id?'primary':'outline'} label={label} onPress={()=>setLevel(id)} />)}</View><Text style={st.copy}>Publica nome do time, esporte, nível e janela. Não publica o elenco.</Text><Button small label="Publicar janela do time" disabled={busy||!date||!team} onPress={()=>void create('window')} /></>}
      {fields.length>0&&<><Text style={st.title}>Meu campo tem horário vago</Text><View style={st.row}>{fields.map(f=><Button key={f.id} small variant={field===f.id?'primary':'outline'} label={f.name} onPress={()=>setField(f.id)} />)}</View><TextField label="Duração (min)" value={duration} onChangeText={setDuration} keyboardType="number-pad" /><TextField label="Preço habitual do horário (R$)" value={regular} onChangeText={setRegular} keyboardType="decimal-pad" /><TextField label="Preço de oportunidade (R$)" value={price} onChangeText={setPrice} keyboardType="decimal-pad" /><Button small label="Publicar horário com desconto" disabled={busy||!date||!field} onPress={()=>void create('slot')} />{data.slots.filter(s=>fields.some(f=>f.id===s.field_id)).map(s=><Button small key={s.id} variant="ghost" label={`Retirar ${s.field_name} · ${new Date(s.starts_at).toLocaleString('pt-BR')}`} onPress={()=>void run('slot_hide',{id:s.id})} />)}</>}
      {!mine.length&&!fields.length&&<Text style={st.copy}>Crie um time ou estabelecimento para publicar.</Text>}
    </Card>}
    {mode==='requests'&&<>{!data.requests.length&&<Text style={st.copy}>Nenhum pedido disponível.</Text>}{data.requests.map(r=>{const venueOwner=app.establishments.some(e=>e.ownerPlayerId===app.currentPlayerId&&app.fields.some(f=>f.establishmentId===e.id&&f.id===data.slots.find(s=>s.id===r.slot_id)?.field_id));return <Card key={r.id} style={st.card}><Text style={st.title}>{r.team_name}{r.opponent_name?` × ${r.opponent_name}`:''}</Text><Text style={st.copy}>{r.field_name} · {new Date(r.starts_at).toLocaleString('pt-BR')} · {formatBRL(r.price)}</Text><Text style={st.copy}>{r.status==='confirmed'?'Reserva confirmada; pagamento a combinar':r.status==='pending'?r.opponent_pelada_id&&!r.opponent_accepted?'Aguardando outro time':'Aguardando campo':r.status==='declined'?'Recusada':'Cancelada'}</Text><Text style={st.copy}>Comissão configurada: {r.commission_percent}%. Não é cobrada por este fluxo; confirmação não comprova receita nem pagamento.</Text>
        {r.status==='pending'&&<View style={st.row}>{r.opponent_pelada_id&&app.isAdmin(app.currentPlayerId,r.opponent_pelada_id)&&!r.opponent_accepted&&<><Button small label="Aceitar desafio" disabled={busy} onPress={()=>void run('opponent_respond',{id:r.id,accept:true})} /><Button small variant="outline" label="Recusar desafio" disabled={busy} onPress={()=>void run('opponent_respond',{id:r.id,accept:false})} /></>}{venueOwner&&<><Button small label="Confirmar horário" disabled={busy||!!r.opponent_pelada_id&&!r.opponent_accepted} onPress={()=>void run('slot_respond',{id:r.id,accept:true})} /><Button small variant="outline" label="Recusar horário" disabled={busy} onPress={()=>void run('slot_respond',{id:r.id,accept:false})} /></>}{app.isAdmin(app.currentPlayerId,r.pelada_id)&&<Button small variant="ghost" label="Cancelar solicitação" disabled={busy} onPress={()=>void run('request_cancel',{id:r.id})} />}</View>}
        {r.match_id&&<Button small label="Abrir partida" onPress={()=>router.push(`/desafio/${r.match_id}`)} />}
      </Card>;})}</>}
  </Screen>;
}
