import { useEffect, useState } from 'react';
import { Share, Switch, Text, View } from 'react-native';
import * as Linking from 'expo-linking';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { TextField } from '@/components/ui/TextField';
import { SegmentedControl } from '@/components/ui/SegmentedControl';
import { colors, spacing } from '@/constants/theme';
import { openGameAdminData, publishOpenGame, respondOpenGameRequest, type OpenGameAdminData } from '@/lib/discovery';

export function OpenGameSection({ gameId }: { gameId: string }) {
  const [data, setData] = useState<OpenGameAdminData | null>(null);
  const [published, setPublished] = useState(false); const [description, setDescription] = useState(''); const [level, setLevel] = useState('all');
  const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  async function refresh() { const next = await openGameAdminData(gameId); setData(next); setPublished(next.listing?.published ?? false); setDescription(next.listing?.description ?? ''); setLevel(next.listing?.level ?? 'all'); }
  useEffect(() => { let live = true; void openGameAdminData(gameId).then(next => { if(!live) return; setData(next); setPublished(next.listing?.published ?? false); setDescription(next.listing?.description ?? ''); setLevel(next.listing?.level ?? 'all'); }).catch(() => { if(live) setNotice('Publicação indisponível. Verifique se as migrações foram aplicadas.'); }); return () => { live = false; }; }, [gameId]);
  async function run(action: () => Promise<unknown>, message: string) { setBusy(true); try { await action(); await refresh(); setNotice(message); } catch(e) { setNotice(e instanceof Error ? e.message : 'Não foi possível concluir.'); } finally { setBusy(false); } }
  async function share() { const base = process.env.EXPO_PUBLIC_APP_WEB_URL?.replace(/\/$/, ''); const url = base ? `${base}/descobrir?gameId=${encodeURIComponent(gameId)}` : Linking.createURL('/descobrir', { queryParams: { gameId } }); await Share.share({ message: `Bora jogar? Temos uma chamada aberta no BoraJogo. Solicite sua participação: ${url}` }); }
  return <Card style={{ marginBottom: spacing.md, gap: spacing.sm }}><Text style={{ fontSize: 16, color: colors.text, fontWeight: '800' }}>Abrir o jogo para novas pessoas</Text><Text style={{ color: colors.textMuted, fontSize: 12, lineHeight: 18 }}>A divulgação mostra time, local, horário e estimativa do rateio. A entrada precisa da sua aprovação; dados dos participantes não ficam na vitrine.</Text><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={{ flex: 1, color: colors.text }}>Divulgar na descoberta</Text><Switch value={published} onValueChange={setPublished} disabled={busy || !data} /></View><SegmentedControl value={level} onChange={setLevel} options={[{ value:'all', label:'Todos' }, { value:'beginner', label:'Iniciante' }, { value:'intermediate', label:'Interm.' }, { value:'advanced', label:'Avançado' }]} /><TextField label="Como é o grupo?" value={description} onChangeText={setDescription} multiline maxLength={500} placeholder="Ex.: jogo tranquilo, iniciantes são bem-vindos" /><Button small label="Salvar divulgação" loading={busy} disabled={!data} onPress={() => void run(() => publishOpenGame(gameId,published,level,description), published ? 'Jogo divulgado. Solicitações aparecerão abaixo.' : 'Divulgação desativada.')} />{data?.listing?.published && <Button small variant="outline" label="Compartilhar chamada" onPress={() => void share().catch(() => setNotice('Não foi possível abrir o compartilhamento.'))} />}{data?.requests.filter(r => r.status === 'pending').map(r => <View key={r.id} style={{ gap: 8 }}><Text style={{ color: colors.text }}>{r.name} quer participar</Text><View style={{ flexDirection:'row', gap: 8 }}><Button small disabled={busy} label="Aprovar entrada" onPress={() => void run(() => respondOpenGameRequest(r.id,true),'Entrada aprovada. Se a chamada estiver cheia, o jogador entra na espera.')} /><Button small disabled={busy} variant="ghost" label="Recusar" onPress={() => void run(() => respondOpenGameRequest(r.id,false),'Solicitação recusada.')} /></View></View>)}<Button small variant="ghost" label="Atualizar solicitações" loading={busy} onPress={() => void run(() => Promise.resolve(),'Solicitações atualizadas.')} />{!!notice && <Text style={{ color:colors.secondary, fontSize:12, lineHeight:18 }}>{notice}</Text>}</Card>;
}
